Library/config/routes.rb
Rails.application.routes.draw do
	resources :readers

   root 'readers

end

Library/app/models/reader.rb
class Reader < ActiveRecord::Base
end

Library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Library/app/controllers/readers_controller.rb
class ReadersController < ApplicationController
	def index
		@readers = Reader.all
	end

	def show
		@reader = Reader.find(params[:id])
	end

	def new
		@reader = Reader.new
	end

	def create
		@reader = Reader.new(reader_params)
		if @reader.save
			redirect_to readers_path, :notice => "New reader has been created.", :color => "valid"
		else
			render "new"
		end
	end

	def edit
		@reader = Reader.find(params[:id])
	end

	def update
		@reader = Reader.find(params[:id])
		if @reader.update_attributes(reader_params)
			redirect_to readers_path, :notice => "Reader status has been updated."
		else
			render "edit"
		end
	end

	def destroy
		@reader = Reader.find(params[:id])
		@reader.destroy
		redirect_to readers_path, :notice => "Reader has been deleted."
	end

	private

	def reader_params
        params.require(:reader).permit(:first_name, :last_name, :date_of_birth, :program, :reg_location, :reg_date,
                                       :mid_date, :mid_location, :mid_initial, :end_date, :end_location, :end_initial)
	end
end

Library/app/helpers/application_helper.rb
module ApplicationHelper
end

Library/app/helpers/readers_helper.rb
module ReadersHelper
end

Library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<p><%= value%></p>
<% end %>

<%= yield %>

</body>
</html>

Library/app/views/readers/edit.html.erb
<h1>Update Information</h1>

<%= form_for @reader do |form| %>
	<h2>Personal Information</h2>
	<p>
		<%= form.label :first_Name %>
		<%= form.text_field :first_name %>
	</p>
	<p>
		<%= form.label :last_name %>
		<%= form.text_field :last_name %>
	</p>
	<p>
		<%= form.label :date_of_birth %>
		<%= form.text_field :date_of_birth %>
	</p>
	<p>
		<%= form.label :program %>
		<%= form.text_field :program %>
	</p>
	<p>
		<%= form.label :location %>
		<%= form.text_field :reg_location %>
	</p>
	<p>
		<%= form.label :register_date %>
		<%= form.text_field :reg_date %>
	</p>
	<hr />
	<h2>Halfway Status</h2>
	<p>
		<%= form.label :date %>
		<%= form.text_field :mid_date %>
	</p>
	<p>
		<%= form.label :location %>
		<%= form.text_field :mid_location %>
	</p>
	<p>
		<%= form.label :initial %>
		<%= form.text_field :mid_initial %>
	</p>	
	<hr />
	<h2>Final Status</h2>
	<p>
		<%= form.label :date %>
		<%= form.text_field :end_date %>
	</p>
	<p>
		<%= form.label :location %>
		<%= form.text_field :end_location %>
	</p>
	<p>
		<%= form.label :initial %>
		<%= form.text_field :end_initial %>
	</p>
	<p>
		<%= form.submit 'Update' %>
		<%= link_to 'Back', readers_path %>
	</p>
<% end %>

Library/app/views/readers/index.html.erb
<h1>Reader Lists</h1>

<% @readers.each do |reader| %>
	<p>Name: <%= link_to reader.first_name + ' ' + reader.last_name, reader %></p>
	<p>
		<%= link_to "Edit", edit_reader_path(reader) %>
		<%= link_to "Delete", reader, method: :delete, data: {confirm: 'Are you sure?'} %>
	</p>
	<hr />
<% end %>

<p><%= link_to "Add a New Reader", new_reader_path %></p> 

Library/app/views/readers/new.html.erb
<h1>Add a New Reader</h1>

<%= form_for @reader do |form| %>
	<p>
		<%= form.label :first_Name %>
		<%= form.text_field :first_name %>
	</p>
	<p>
		<%= form.label :last_name %>
		<%= form.text_field :last_name %>
	</p>
	<p>
		<%= form.label :date_of_birth %>
		<%= form.text_field :date_of_birth %>
	</p>
	<p>
		<%= form.label :program %>
		<%= form.text_field :program %>
	</p>
	<p>
		<%= form.label :location %>
		<%= form.text_field :reg_location %>
	</p>
	<p>
		<%= form.label :register_date %>
		<%= form.text_field :reg_date %>
	</p>
	<p>
		<%= form.submit "Create" %>
		<%= link_to 'Back', readers_path %>
	</p>
<% end %>

Library/app/views/readers/show.html.erb
<h1>Reader Information</h1>

<h2>Personal Information</h2>

<p>First Name: <%= @reader.first_name %></p>
<p>Last Name: <%= @reader.last_name %></p>
<p>Date of Birth: <%= @reader.date_of_birth %></p>
<p>Program: <%= @reader.program %></p>
<p>Registration Location: <%= @reader.reg_location %></p>

<hr />
<h2>Halfway Status</h2>
<p>Date: <%= @reader.mid_date %></p>
<p>Location: <%= @reader.mid_location %></p>
<p>Initial: <%= @reader.mid_initial %></p>

<hr />
<h2>Final Status</h2>
<p>Date: <%= @reader.end_date %></p>
<p>Location: <%= @reader.end_location %></p>
<p>Initial: <%= @reader.end_initial %></p>

<p>
	<%= link_to 'Back', readers_path %>
</p>